- .github/workflows/manual-test.yml
Adds a workflow that can be triggered manually on any branch to test changes. That's the idea anyway.
I'm going to merge this myself without waiting for review as it's just adding a new workflow that's only triggered by `workflow_dispatch`. This will let me try it out and once it's on the default branch I should be fix any bugs by running the workflow against another branch before pushing any fixes.
cc @rneatherway for info
> Add workflow for manual testing

- .github/workflows/manual-test.yml
Turns out the actions UI for triggering a workflow dispatch doesn't like newlines. As far as I can tell it just can't handle them.
This change means that if you trigger the workflow from the API without any inputs then it works. And you can specify newlines in the query if using the API. I think unfortunately this workflow will just have to be API-only as I think that being able to specify the query text if a necessity.
> Fix manual test workflow

- .github/workflows/codeql-query.yml
Swap out the call to `codeql-action/init` for just using the CodeQL bundle built in to the actions images. It's known that this won't work on self-hosted runners, but that's a concern for the future and we're happy to just deal with it later.
This should theoretically be all that's needed to use a controller repository that doesn't have GHAS enabled.
> Avoid using codeql-action to initialise codeql

- .github/workflows/codeql-query.yml
We can limit the scopes that the actions token has, rather than giving it full write permissions to the `github/codeql-variant-analysis-action` repository. I think that the only job that needs any permissions at all is when we create the issue at the end. The proof will be in testing it though.
> Add permissions blocks to workflow jobs

- .github/workflows/codeql-query.yml
- .github/workflows/integration-test-call.yml
- .github/workflows/integration-test-trigger.yml
- .github/workflows/pr-checks.yml
This is an idea to reduce the chance of forgetting to run the integration tests. It's not perfect but hopefully it'll do enough to make us not forget.
The idea is that you're most likely to just forget to run the tests at all. Once you've done it once by updating the action branch and running the tests you're more likely to remember to run them again if you make any big changes to the PR. Therefore once the tests have run once with the correct action branch it adds a label to the PR. Then there's another CI check that checks for the presence of the label.
It's worth noting that this approach isn't perfect. It won't make you run the tests again if you make any changes. There are other approaches we could take to solve the problem of it being tedious to run the tests and easy to forget. …
> Add a label to PRs once tests have passed once

- .github/workflows/integration-test-call.yml
- .github/workflows/integration-tests-label.yml
- .github/workflows/pr-checks.yml
Hopefully fixed the problems from https://github.com/github/codeql-variant-analysis-action/pull/720
The `integration-tests-have-been-run` check now runs when a label is added to the PR so it'll update its state.
The "Add success label to pull request" step now only adds the label if the workflow references the current branch.
> Adjustments to integration tests label check

- .github/workflows/script/check-node-modules.sh
What do people think of this? Is this enough of a warning to help us remember how to do things?
I'm also not actually sure if linux is strictly needed as windows might work too. All I know currently is that mac doesn't work.
> Update check-node-modules.sh to mention running on linux

- .github/workflows/codeql-query.yml
When in live-results mode, we don't upload actions artifacts, but the `combine-results` job fails if there are no artifacts. But we don't actually need to run the `combine-results` job at all now, so it's purpose is now handled by the github API.
I think doing `always()` and another condition is valid syntax here. Weirdly it would have different behaviour to just the condition on it's own, because actions adds an implicit `if: success()` unless you use `always()` or `failure()`. See https://stackoverflow.com/questions/58858429 and https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions for more info.
We / I should ideally do some tests of this too and make sure it does behave as expected. If we can't get this condition to work, we could also just put the …
> Skip combine-results step if we have a variant analysis ID

- .github/workflows/integration-test-trigger.yml
In a PR, we should be using `${{ github.event.pull_request.head.sha }}` to ensure we are creating the status on the commit of the PR, rather than on the automatically created merge commit.
See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
> Use the correct SHA for status checks in PRs

- .github/workflows/codeql-query.yml
- .github/workflows/integration-tests.yml
This PR should remove these deprecation warnings:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See internal issue too! 😊
> Replace deprecated `set-output` syntax with `GITHUB_OUTPUT`

- .github/workflows/integration-tests.yml
This will add a link to the variant analysis Actions workflow to make it easier to debug when the integration test does fail. It also adds a check for the status and conclusion of the Actions workflow to ensure it did not fail.
> Add Actions link and validate Actions status

- .github/workflows/integration-tests.yml
The variant analysis status enum has been updated. This will change the integration tests to use the correct new status.
> Use new variant analysis statuses in integration tests

- .github/workflows/codeql-query.yml
- query/action.yml
- update-repo-task-status/action.yml
🧹 Cleans up code that doesn't get used:
- We no longer need `security-events: write` permission for the MRVA endpoints
- We no longer have a `token` field in the `repositories` object
- Ideally, we'd also get rid of `pat`, since that only [gets used in old integration tests](https://github.com/github/codeql-variant-analysis-action/blob/2e07ba3fbddcede187f3b53f552c425189b76f83/.github/workflows/codeql-query.yml#L80-L82). We can remove that once live results is fully available.
See internal linked issue for details!
> Remove deprecated code

- .github/workflows/codeql-query.yml
This adds the environment variable that enables Swift support to all variant analysis queries. Swift support for MRVA will still be gated by other means in the VSCode extension.
> Add experimental Swift support

- .github/workflows/codeql-query.yml
Example run with re-running only failed jobs: https://github.com/github/codeql-variant-analysis-action/actions/runs/3628283507/attempts/2
Example run with re-running setup job: https://github.com/github/codeql-variant-analysis-action/actions/runs/3628283507/attempts/3
> Do not allow reruns of the workflow

- .github/workflows/codeql-query.yml
- query/action.yml
- update-repo-task-status/action.yml
- update-repo-task-statuses/action.yml
The signed auth token was not actually being passed into the action because the input was missing. This adds the signed auth token as an input into the appropriate actions. This should have no impact for runs without a signed auth token.
> Use signed auth token

- node_modules/.package-lock.json
- script/generate-json-schemas
This PR aims to get the CI working again. I think what's happened is that the version of Node/NPM used on actions runners has increased. We now need to upgrade our lock file in order to get CI to pass again. I'm also hitting issues when generating json schemas.
I generated the package lock change by running `npm ci && npm run removeNPMAbsolutePaths` from a codespace.
The node/npm versions are:
| | codespace | actions |
|---|---|---|
| Node | 19.8.1 | 18.16.0 |
| NPM | 9.5.1 | 9.5.1 |
> Fix CI after node/npm versions have changed

- .github/workflows/codeql-query.yml
These are no longer required since we're using signed auth tokens.
> Remove required permissions from jobs

- .eslintrc.json
- package-lock.json
- package.json
- script/find-deadcode.ts
- tsconfig.json
- tsconfig.lint.json
This adds a script for finding dead code using `ts-unused-exports`. It also adds `ts-node` for running the script.
The script itself is very similar to [the one in vscode-codeql](https://github.com/github/vscode-codeql/blob/d3df14f860b81424c43f911a9ec765240f6b55c0/extensions/ql-vscode/scripts/find-deadcode.ts), but it does not ignore any files.
> Add script for finding dead code

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
The CodeQL analysis is run on the `dist` directory causing a lot of false positives. This excludes the `dist` directory and makes it scan `src` instead.
> Exclude `dist` from CodeQL analysis

- dist/query.js
- src/query.ts
When your query gets stuck because it has terrible performance on a specific project, it is much easier to debug when it's possible to see the name of the repository
> Show repo name when downloading database

- dist/query.js
- dist/update-repo-task-status.js
- dist/update-repo-task-statuses.js
- src/codeql.ts
- src/json-schemas/QueryMetadata.json
This changes the `codeql bqrs interpret` call to use the original query metadata rather than passing in only a fixed `-t=id=remote-query` argument. This should make MRVA behave more like running a local query since this is [what we also do in the VS Code extension](https://github.com/github/vscode-codeql/blob/31e233cc59c71c664b39d39d40b40f03e13e1737/extensions/ql-vscode/src/codeql-cli/cli.ts#L1057).
We still need to ensure that there is an ID passed in since interpreting a SARIF file requires an ID, so we still have a fallback if we do execute a query without an ID (I'm not sure if that's possible though).
> Use original query metadata

- dist/query.js
- src/codeql.ts
When the `qlpack.yml` file didn't exist, `fs.statSync` would throw an error. Therefore, we would never check if the `codeql-pack.yml` exists.
This fixes it by using the `throwIfNoEntry` option of `fs.statSync`.
> Fix support for `codeql-pack.yml` file

- variant-analysis-workflow.yml
The idea here is to make it so that the GitHub API can read and execute this workflow file directly, instead of calling it as a callable workflow.
The aim is to move the file out of the `.github/workflows` directory because it isn't really a workflow that's executed in the normal way. It's just a YAML file that happens to contain workflow code. For now, this PR duplicates the file and leaves the old one alone. This will make it easier to deploy and roll back if needed, rather than having to merge this at the same time as the API change.
See the internal github PR for the other side of this change.
> Make variant analysis workflow so it can be executed directly as a dynamic workflow

- variant-analysis-workflow.yml
This fixes MRVA when using the new feature of reading the dynamic workflow directly from this repo. Unfortunately the `name` field cannot use expressions, so workflow runs were failing. Instead we can use `run-name` which does work with expressions.
Currently this feature is only enabled on my private test controller repo, but I have screenshots of a successful run I did using this branch.
> Use run-name which can accept dynamic expressions

- dist/query.js
- src/query.ts
This is a repeat of https://github.com/github/codeql-variant-analysis-action/pull/853
Only call `uploadRepoResult` if there are results. This function is what makes the `/artifact` API request and uploads the artifact contents to azure. So without it we only do the request that sets the repo task status to "succeeded".
See the corresponding API change that makes it handle repo tasks that are succeeded without an artifact uploaded. This PR should not be merged until the API is updated.
> Only upload results if there are any

- dist/query.js
- src/codeql.ts
Remove `bqrsFileSize` and `sarifFileSize` from `RunQueryResult` as they don't actually seem to be used anywhere.
> Remove unused file size fields from RunQueryResult

- CONTRIBUTING.md
Added a call out to `script/test` that I wasn't aware of before @shati-patel mentioned it to me.
> Add running tests section in CONTRIBUTING guide

- dist/query.js
- src/codeql.ts
- src/query.ts
Everywhere we currently have a variable named `queryPack` I've renamed it to `queryPackPath`, as in all cases this is what the variable contained. I did also consider `queryPackDir`, but we have a number of existing `queryPackPath` variables in this repo so I decided to stay consistent with those and not change too much in this PR.
> Rename queryPack => queryPackPath

- dist/query.js
- src/codeql.test.ts
- src/codeql.ts
MRVA fails when running certain queries, such as [`IncompleteHostnameRegExp.ql`](https://github.com/github/codeql/blob/main/python/ql/src/Security/CWE-020/IncompleteHostnameRegExp.ql). This is because the resulting BQRS file doesn't contain a `#select` results set but instead contains one called `problems`.
This PR allows us to use either results set. In my manual searches, every query I've looked at has precisely one of these two.
I've tested this PR by confirming that `IncompleteHostnameRegExp.ql` fails when using the `main` branch of this repo, but passes when using this branch. I then also tested this branch with another `problem` query, a `path-problem` query, a `table` query, and also tried running against the published pack for python.
---
I've also opened an internal issue to look …
> Read problems result set if '#select' result set doesn't exist

- dist/query.js
- dist/update-repo-task-status.js
- dist/update-repo-task-statuses.js
- package-lock.json
- package.json
- src/gh-api-client.ts
- variant-analysis-workflow.yml
This pull request primarily focuses on enhancing the rate limit handling in the `gh-api-client.ts` file by integrating the `@octokit/plugin-throttling` library. It also includes a minor change to the `variant-analysis-workflow.yml` file to set an environment variable.
Rate limit handling enhancement:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R37): Added `@octokit/plugin-throttling` to the list of dependencies.
* [`src/gh-api-client.ts`](diffhunk://#diff-edee0dd739a0d285c7e996010b790ae84a434a4629984aed47ca48b1aad6c135R4): Imported the `throttling` function from `@octokit/plugin-throttling`.
* [`src/gh-api-client.ts`](diffhunk://#diff-edee0dd739a0d285c7e996010b790ae84a434a4629984aed47ca48b1aad6c135L15-R48): Refactored the …
> Add octokit throttling behind env var

- dist/query.js
- src/azure-client.ts
When we get a request timeout while uploading an artifact, a [request timeout error is created by the Actions HTTP client](https://github.com/actions/toolkit/blob/415c42d27ca2a24f3801dd9406344aaea00b7866/packages/http-client/src/index.ts#L535). We want to retry on this error since this is very likely to be transient. Unfortunately, it's not a custom error which we can check against, so we need to match against the message.
> Retry request timeout errors

- dist/query.js
- src/codeql.ts
This PR aims to make `queryPackSupportsSarif` easier to read, and fixes the comment which was unfortunately giving wrong information.
> Simplify queryPackSupportsSarif and fix comment

- dist/query.js
- src/codeql-cli.test.ts
- src/codeql-cli.ts
- src/codeql.test.ts
- src/codeql.ts
- src/query.ts
- variant-analysis-workflow.yml
This PR adds the ability to use the CodeQL CLI server for running commands. This results in better performance of individual command invocations since there's less JVM overhead. On a test I ran, the overhead (defined as time not spent running `codeql database run-queries`) went down from 20% to 3-5%.
This is currently guarded by the `MRVA_USE_CLI_SERVER` repo Actions variable. We can probably remove this in a follow-up PR once this has been sufficiently tested.
> Use the CodeQL CLI server for running CodeQL commands

- dist/query.js
- src/codeql.test.ts
- src/codeql.ts
This adds support for the `alert` and `path-alert` aliases to treat them as `problem` and `path-problem`, respectively.
> Add support for alert and path-alert aliases

- dist/query.js
- src/codeql.ts
This adds support for GHEC-DR. It replaces hardcoded `github.com` URLs by [the environment variables available in Actions](https://docs.github.com/en/actions/learn-github-actions/variables) with a fallback to the current value. This matches [what `@octokit/action` does](https://github.com/octokit/action.js/blob/aee7aaedceedcf7cd64db65cc9aff03bf95f3f25/src/index.ts#L56C10-L56C67). Since `@octokit/action` already does this, we don't need to make any changes to Octokit constructors and this is handled automatically.
> Add support for GHEC-DR

- package-lock.json
I ran `npm upgrade eslint-plugin-escompat` to upgrade this dependency which should unblock https://github.com/github/codeql-variant-analysis-action/pull/1091.
> Upgrade eslint-plugin-escompat to v3.11.3

- package-lock.json
- package.json
The action is [still running](https://github.com/github/codeql-variant-analysis-action/blob/0fc08f096774edf4331e9e13aba0bb3d280898fa/query/action.yml#L34) on Node 20, so we should be using `@types/node` v20, not v22.
> Downgrade @types/node to v20
